baseurl = "http://ytop.net"  # Include trailing slash
title = "Luke's blog"
theme = "newsroom"
author = "Luke"
copyright = "Copyright Â© 2020 Luke. All rights reserved."
canonifyurls = true
paginate = 5
isCJKLanguage= true
# Enable syntax highlighting
# comment or delete lines 11 ~ 14
pygmentsCodefences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses=true
pygmentsOptions = "linenos=table"

# Alternatively, you can use chroma instead of pigments
# to do so comment or delete lines 11 ~ 14 and uncomment lines 17 ~ 27
# [markup]
#   [markup.highlight]
#     codeFences = true
#     guessSyntax = false
#     hl_Lines = ""
#     lineNoStart = 1
#     lineNos = true
#     lineNumbersInTable = true
#     noClasses = false
#     style = "monokai"
#     tabWidth = 4

# If you want to use disqus, uncomment the line below
disqusShortname = "ytop"

# ids used below are not valid. Replace with valid ones
[params]
  # logo = "stuck.jpg"
  # ga_analytics = "" # google analytics ID e.g UA-116386578-1

  # ga_verify = "" # google verification code e.g 5jb-rxeBfITeJQKOuUss3ud6FPGTxXkCho-ZN5qlrZg
  twitter = "@ytopnet" # twitter handle e.g @weru

